"""Prove the Alembic migration reproduces schema.sql for the Phase-1 tables.

sql/schema.sql is the human-readable reference for what the database should
look like; the migration is what actually builds it. Those two can drift, and
nothing would notice. This script makes the comparison mechanical:

  1. build a throwaway database from sql/schema.sql,
  2. read the live migrated database,
  3. diff columns, constraints and indexes for the 8 in-scope tables, plus the
     enum types they use.

    python scripts/verify_schema.py

Exits non-zero on any difference. Tables belonging to Phases 2-6 are ignored:
schema.sql legitimately has 21 tables, Phase 1 legitimately has 8.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import psycopg

from app.core.config import settings

BACKEND_DIR = Path(__file__).resolve().parent.parent
SCHEMA_SQL = BACKEND_DIR / "sql" / "schema.sql"

PHASE1_TABLES = [
    "users",
    "refresh_tokens",
    "pgs",
    "buildings",
    "floors",
    "rooms",
    "beds",
    "staff_assignments",
]
PHASE1_ENUMS = ["user_role", "room_type", "bed_status", "pg_gender_type"]

REFERENCE_DB = "phase1_schema_reference"


def _dsn(database: str) -> str:
    """Plain libpq DSN for `database` on the configured server."""
    url = settings.sync_database_url.replace("postgresql+psycopg://", "postgresql://")
    base, _, _ = url.rpartition("/")
    return f"{base}/{database}"


def _admin_dsn() -> str:
    return _dsn("postgres")


def build_reference_database() -> None:
    """(Re)create REFERENCE_DB and run schema.sql into it."""
    with psycopg.connect(_admin_dsn(), autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{REFERENCE_DB}"')
        conn.execute(f'CREATE DATABASE "{REFERENCE_DB}"')

    raw = SCHEMA_SQL.read_text(encoding="utf-8")
    stripped = "\n".join(re.sub(r"--.*$", "", line) for line in raw.splitlines())
    statements = [s.strip() for s in stripped.split(";") if s.strip()]

    with psycopg.connect(_dsn(REFERENCE_DB), autocommit=True) as conn:
        for index, statement in enumerate(statements, start=1):
            try:
                conn.execute(statement)
            except Exception as exc:  # pragma: no cover - reported, not swallowed
                print(f"schema.sql statement #{index} failed:\n{statement}\n  -> {exc}")
                raise


def read_structure(dsn: str) -> dict:
    out: dict = {"tables": {}, "enums": {}}
    with psycopg.connect(dsn) as conn:
        for table in PHASE1_TABLES:
            columns = conn.execute(
                """
                SELECT column_name, udt_name, is_nullable, character_maximum_length,
                       numeric_precision, numeric_scale
                FROM information_schema.columns
                WHERE table_name = %s AND table_schema = 'public'
                ORDER BY column_name
                """,
                (table,),
            ).fetchall()

            constraints = conn.execute(
                """
                SELECT pg_get_constraintdef(con.oid)
                FROM pg_constraint con
                JOIN pg_class rel ON rel.oid = con.conrelid
                JOIN pg_namespace ns ON ns.oid = rel.relnamespace
                WHERE rel.relname = %s AND ns.nspname = 'public'
                """,
                (table,),
            ).fetchall()

            indexes = conn.execute(
                """
                SELECT indexdef FROM pg_indexes
                WHERE tablename = %s AND schemaname = 'public'
                """,
                (table,),
            ).fetchall()

            out["tables"][table] = {
                "columns": {c[0]: tuple(c[1:]) for c in columns},
                # Constraint *names* differ harmlessly between a hand-written
                # CREATE TABLE and an autogenerated migration; the definitions
                # are what must match, so compare those as a set.
                "constraints": {c[0] for c in constraints},
                "indexes": {_normalise_index(i[0]) for i in indexes},
            }

        for enum_name in PHASE1_ENUMS:
            labels = conn.execute(
                """
                SELECT e.enumlabel
                FROM pg_type t JOIN pg_enum e ON e.enumtypid = t.oid
                WHERE t.typname = %s
                ORDER BY e.enumsortorder
                """,
                (enum_name,),
            ).fetchall()
            out["enums"][enum_name] = [row[0] for row in labels]

    return out


def _normalise_index(indexdef: str) -> str:
    """Drop the index's own name, keep what it actually indexes."""
    match = re.search(r"ON (.*)$", indexdef)
    return match.group(1) if match else indexdef


def compare(reference: dict, actual: dict) -> list[str]:
    problems: list[str] = []

    for table in PHASE1_TABLES:
        ref, act = reference["tables"][table], actual["tables"][table]

        if not ref["columns"]:
            problems.append(f"[{table}] missing from the reference database")
            continue
        if not act["columns"]:
            problems.append(f"[{table}] missing from the migrated database")
            continue

        missing = set(ref["columns"]) - set(act["columns"])
        extra = set(act["columns"]) - set(ref["columns"])
        if missing:
            problems.append(f"[{table}] columns missing after migration: {sorted(missing)}")
        if extra:
            problems.append(f"[{table}] unexpected extra columns: {sorted(extra)}")

        for column in sorted(set(ref["columns"]) & set(act["columns"])):
            if ref["columns"][column] != act["columns"][column]:
                problems.append(
                    f"[{table}.{column}] type/nullability differs: "
                    f"schema.sql={ref['columns'][column]} migration={act['columns'][column]}"
                )

        for label, key in (("constraints", "constraints"), ("indexes", "indexes")):
            ref_only = ref[key] - act[key]
            act_only = act[key] - ref[key]
            if ref_only:
                problems.append(f"[{table}] {label} in schema.sql but not migrated: {sorted(ref_only)}")
            if act_only:
                problems.append(f"[{table}] {label} created by migration but not in schema.sql: {sorted(act_only)}")

    for enum_name in PHASE1_ENUMS:
        if reference["enums"][enum_name] != actual["enums"][enum_name]:
            problems.append(
                f"[enum {enum_name}] differs: schema.sql={reference['enums'][enum_name]} "
                f"migration={actual['enums'][enum_name]}"
            )

    return problems


def main() -> int:
    print(f"Building reference database from {SCHEMA_SQL.relative_to(BACKEND_DIR)} ...")
    build_reference_database()

    reference = read_structure(_dsn(REFERENCE_DB))
    actual = read_structure(settings.sync_database_url.replace("postgresql+psycopg://", "postgresql://"))

    problems = compare(reference, actual)
    if problems:
        print(f"\nFAIL — {len(problems)} difference(s) between schema.sql and the migration:\n")
        for problem in problems:
            print("  -", problem)
        return 1

    print(
        f"\nOK — all {len(PHASE1_TABLES)} Phase-1 tables and "
        f"{len(PHASE1_ENUMS)} enum types match schema.sql exactly."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
